### ISSUE TITLE
Handle new lines from all operating systems

### ISSUE THREAD

**Issue by andreashasse** [jabberbees/egherkin#1]
Hi!

Great repository! I was looking for a good bdd library for erlang/elixir and came across this. Do you know if it is used in any testing libraries?
From how I understand it the code assumes that line breaks are \r\n. But on some operating systems it is \n. There is also some handling of rows ending with \n that doesn't seem to work. Are you open to a PR where I make the handling of \r\n and \n the same and remove the special handling of \n? I will of course include tests and stuff :)

**Comment by eboutin** [comment]
Hi, thanks for the comment. I have no knowledge on this lib usage. A PR to handle line breaks on all operating systems would be great, of course!
